apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "cmc-claim-store"
  annotations:
    # This must match folder-name/job-name in Jenkins.
    jenkins.io/job-full-name: cft:HMCTS_a_to_c/cmc-claim-store
    github.com/project-slug: hmcts/cmc-claim-store
  tags:
    - java
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=cmc-tech
      title: "#cmc-tech on Slack"
      icon: chat
spec:
  type: service
  lifecycle: production
  owner: dts_civil
