ignore:
  - "**/cmc/domain/models/**"
  - "**/cmc/claimstore/idam/models/**"
  - "**/config/**"
  - "**/*Exception.java"
  - "**/ExceptionForClient.java"
  - "**/*Event.java"
  - "**/ClaimRepository.java"
  - "**/PathPatterns.java"
  - "**/cmc/claimstore/appinsights/**"
  - "**/ccd/domain/**"
  - "**/ccd/deprecated/**,"
  - "**/ccd/jackson/mixin/**"
  - "**/ccd/migration/**"
  - "**/EmailData.java"
  - "**/cmc/ccd/mapper/**"
