ignore:
  - "**/ValidInterestConstraintValidator.java"
  - "**/ValidInterestDateConstraintValidator.java"
  - "**/ValidUnemploymentConstraintValidator.java"
  - "**/ValidEmploymentConstraintValidator.java"
  - "**/cmc/domain/models/**"
  - "**/cmc/claimstore/idam/models/**"
  - "**/config/**"
  - "**/*Exception.java"
  - "**/ExceptionForClient.java"
  - "**/*Event.java"
  - "**/ClaimRepository.java"
  - "**/CCDCaseRepository.java"
  - "**/PathPatterns.java"
  - "**/cmc/claimstore/appinsights/**"
  - "**/cmc/claimstore/services/ccd/legaladvisor/**"
  - "**/cmc/claimstore/services/ccd/callbacks/ioc/FeesAndPaymentsConfiguration.java"
  - "**/cmc/claimstore/courtfinder/models/**"
  - "**/ccd/domain/**"
  - "**/ccd/sample/data/**"
  - "**/ccd/migration/**"
  - "**/EmailData.java"
  - "**/CCDCaseHandler.java"
  - "**/GeneratedDocuments.java"
  - "**/CCDCaseApi.java"
  - "**/DBCaseRepository.java"
