ignore:
  - "**/cmc/domain/models/**"
  - "**/cmc/claimstore/idam/models/**"
  - "**/config/**"
  - "**/*Exception.java"
  - "**/ExceptionForClient.java"
  - "**/*Event.java"
  - "**/ClaimRepository.java"
  - "**/CCDCaseRepository.java"
  - "**/PathPatterns.java"
  - "**/cmc/claimstore/appinsights/**"
  - "**/cmc/claimstore/services/ccd/legaladvisor/**"
  - "**/ccd/domain/**"
  - "**/ccd/deprecated/**"
  - "**/ccd/migration/**"
  - "**/EmailData.java"
  - "**/CCDCaseHandler.java"
  - "**/GeneratedDocuments.java"
