#!/bin/bash
sonarlint -Dsonar.java.libraries=build/libs \
  --src "{src/main/**,email-client/src/main/**,ccd-adapter/src/main/**,launch-darkly-client/src/main/**}" \
  --tests "{src/test/**,src/apiTest/**,email-client/src/test/**,ccd-adapter/src/test/**,launch-darkly-client/src/test/**}"

