package uk.gov.hmcts.cmc.ccd.domain;

public enum CCDClaimDocumentType {
    ORDER_DIRECTIONS,
    ORDER_SANCTION,
    CLAIM_ISSUE_RECEIPT,
    SEALED_CLAIM,
    DEFENDANT_RESPONSE_RECEIPT,
    CCJ_REQUEST,
    SETTLEMENT_AGREEMENT,
    CLAIMANT_DIRECTIONS_QUESTIONNAIRE,
    REVIEW_ORDER,
    MEDIATION_AGREEMENT,
    PAPER_RESPONSE_FULL_ADMIT,
    PAPER_RESPONSE_PART_ADMIT,
    PAPER_RESPONSE_STATES_PAID,
    PAPER_RESPONSE_MORE_TIME,
    PAPER_RESPONSE_DISPUTES_ALL
}
