# Example Kubernetes resource template
#
# All variables are replaced at deployment time with environment variables.
#
# The following variables are derived as follows by the pipeline. DO NOT CHANGE:
#
#   - NAMESPACE:    product
#   - SERVICE_NAME: product-component-branch
#   - IMAGE_NAME:   registry-name/hmcts/product-component:branch
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
    spec:
      containers:
        - image: ${IMAGE_NAME}
          name: ${SERVICE_NAME}

          # These are obtained from environment variables.  If it's
          # an environment variable, it can be used here.  Projects
          # would usually source custom values from:
          #   - Jenkins Azure Keyvault plugin (e.g. secrets)
          #   - Your project's Jenkinsfile
          env:
            - name: REFORM_TEAM
              value: 'cmc'
            - name: REFORM_SERVICE_NAME
              value: 'claim-store'
            - name: CLAIM_STORE_DB_PORT
              value: '5432'
            - name: CLAIM_STORE_DB_USERNAME
              value: 'claimstore'
            - name: CLAIM_STORE_DB_PASSWORD
              value: "${CLAIM_STORE_DB_PASSWORD}"
            - name: CLAIM_STORE_DB_NAME
              value: 'claimstore'
            - name: CLAIM_STORE_DB_CONNECTION_OPTIONS
              value: '?ssl&sslmode=require'
            - name: CMC_DB_PORT
              value: '5432'
            - name: CMC_DB_NAME
              value: 'cmc'
            - name: CMC_DB_PASSWORD
              value: "${CMC_DB_PASSWORD}"
            - name: CMC_DB_CONNECTION_OPTIONS
              value: '?ssl&sslmode=require'
            - name: IDAM_S2S_AUTH_TOTP_SECRET
              value: "${CLAIM_STORE_S2S_SECRET}"
            - name: IDAM_CASEWORKER_ANONYMOUS_USERNAME
              value: "${ANONYMOUS_CASEWORKER_USERNAME}"
            - name: IDAM_CASEWORKER_ANONYMOUS_PASSWORD
              value: "${ANONYMOUS_CASEWORKER_PASSWORD}"
            - name: IDAM_CASEWORKER_SYSTEM_USERNAME
              value: "${SYSTEM_UPDATE_USERNAME}"
            - name: IDAM_CASEWORKER_SYSTEM_PASSWORD
              value: "${SYSTEM_UPDATE_PASSWORD}"
            - name: OAUTH2_CLIENT_SECRET
              value: "${OAUTH2_CLIENT_SECRET}"
            - name: GOV_NOTIFY_API_KEY
              value: "${NOTIFY_API_KEY}"
            - name: SPRING_MAIL_HOST
              value: 'mta.reform.hmcts.net'
            - name: SPRING_MAIL_PORT
              value: '25'
            - name: SPRING_MAIL_TEST_CONNECTION
              value: 'false'
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
              value: 'true'
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST
              value: 'mta.reform.hmcts.net'
            - name: STAFF_NOTIFICATIONS_SENDER
              value: 'noreply@reform.hmcts.net'
            - name: STAFF_NOTIFICATIONS_RECIPIENT
              value: "${STAFF_EMAIL}"
            - name: RPA_NOTIFICATIONS_SENDER
              value: 'noreply@reform.hmcts.net'
            - name: RPA_NOTIFICATIONS_SEALEDCLAIMRECIPIENT
              value: "${STAFF_EMAIL}"
            - name: RPA_NOTIFICATIONS_MORETIMEREQUESTEDRECIPIENT
              value: "${STAFF_EMAIL}"
            - name: RPA_NOTIFICATIONS_RESPONSERECIPIENT
              value: "${STAFF_EMAIL}"
            - name: RPA_NOTIFICATIONS_COUNTYCOURTJUDGEMENTRECIPIENT
              value: "${STAFF_EMAIL}"
            - name: CLAIM_STORE_TEST_SUPPORT_ENABLED
              value: 'true'
            - name: FEATURE_TOGGLES_EMAILTOSTAFF
              value: 'true'
            - name: ROOT_APPENDER
              value: 'CMC'
          envFrom:
            - configMapRef:
                name: ${SERVICE_NAME}-config

          # These may be adjusted, but be mindful please
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "2500m"

          # This is the port your process is listening on in the container
          ports:
            - containerPort: 4400
              name: http
          imagePullPolicy: Always

# Azure Internal Loadbalancer.
---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      # Make sure targetPort is the same as 'containerPort' above...
      targetPort: 4400
  selector:
    app: ${SERVICE_NAME}
