quartzProperties:
  org.quartz:
    scheduler:
      instanceId: AUTO
    jobStore:
      isClustered: false
      class: org.quartz.impl.jdbcjobstore.JobStoreTX
      driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      dataSource: scheduler
    threadPool:
      class: org.quartz.simpl.SimpleThreadPool
      threadCount: 8

spring:
  datasource:
    scheduler:
      driverClassName: org.postgresql.Driver
      username: ${SCHEDULER_DB_USERNAME:-}
      password: ${SCHEDULER_DB_PASSWORD:-}
      url: jdbc:postgresql://${SCHEDULER_DB_HOST:}:${SCHEDULER_DB_PORT:}/${SCHEDULER_DB_NAME:scheduler}
