idam_api_url = "https://idam-api.aat.platform.hmcts.net"
db_host = "preprod-data-lb.moneyclaim.reform.hmcts.net"
frontend_url = "https://moneyclaim.nonprod.platform.hmcts.net"
capacity = "2"
respond_to_claim_url = "https://moneyclaim.nonprod.platform.hmcts.net/first-contact/start"
