idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
db_host = "preprod-data-lb.moneyclaim.reform.hmcts.net"
frontend_url = "https://moneyclaims.aat.platform.hmcts.net"
capacity = "2"
respond_to_claim_url = "https://moneyclaims.aat.platform.hmcts.net/first-contact/start"
