vault_section = "preprod"
idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
s2s_url = "https://preprod-s2s-api.reform.hmcts.net:3511"
frontend_url = "https://www.moneyclaims.demo.platform.hmcts.net"
respond_to_claim_url = "https://www.moneyclaims.demo.platform.hmcts.net/first-contact/start"
db_host = "preprod-data-lb.moneyclaim.reform.hmcts.net"
