vault_section = "preprod"
idam_api_url = "https://idam-api.demo.platform.hmcts.net"
frontend_url = "https://www.moneyclaims.demo.platform.hmcts.net"
respond_to_claim_url = "https://www.moneyclaims.demo.platform.hmcts.net/first-contact/start"
db_host = "preprod-data-lb.moneyclaim.reform.hmcts.net"
capacity = "2"
enable_staff_email = "false"
dm_url = "http://dm-store-demo.service.core-compute-demo.internal"
