idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
frontend_url = "https://www.moneyclaims.demo.platform.hmcts.net"
respond_to_claim_url = "https://www.moneyclaims.demo.platform.hmcts.net/first-contact/start"
db_host = "preprod-data-lb.moneyclaim.reform.hmcts.net"
capacity = "2"
dm_url = "false"
