idam_api_url = "https://idam-api.ithc.platform.hmcts.net"
frontend_url = "https://moneyclaims.ithc.platform.hmcts.net"
respond_to_claim_url = "https://moneyclaims.ithc.platform.hmcts.net/first-contact/start"
db_host = "preprod-data-lb.moneyclaim.reform.hmcts.net"
capacity = "2"
dm_url = "http://dm-store-ithc.service.core-compute-ithc.internal"
save_claim_state_enabled = "true"
claim_stayed_schedule = "0 0 16 * * 1-5"
