vault_section = "preprod"
idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
db_host = "preprod-data-lb.moneyclaim.reform.hmcts.net"
frontend_url = "https://moneyclaim.nonprod.platform.hmcts.net"
respond_to_claim_url = "https://cmc-citizen-frontend-saat-staging.service.core-compute-saat.internal/first-contact/start"
