idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
db_host = ""
frontend_url = "https://moneyclaim.nonprod.platform.hmcts.net"
respond_to_claim_url = "https://moneyclaim.nonprod.platform.hmcts.net/first-contact/start"
ccd_enabled = "false"
ccd_async_enabled = "true"
