idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
db_host = "cmc-aat.postgres.database.azure.com"
frontend_url = "https://moneyclaim.nonprod.platform.hmcts.net"
respond_to_claim_url = "https://moneyclaim.nonprod.platform.hmcts.net/first-contact/start"
s2s_url = "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
