vault_section = "prod"
idam_api_url = "https://prod-idamapi.reform.hmcts.net:3511"
s2s_url = "https://prod-s2s-api.reform.hmcts.net:3511"
frontend_url = "https://www.moneyclaim.platform.hmcts.net"
db_host = "prod-data-lb.moneyclaim.reform.hmcts.net"
