idam_api_url = "https://prod-idamapi.reform.hmcts.net"
frontend_url = "https://www.moneyclaims.service.gov.uk"
respond_to_claim_url = "https://www.gov.uk/respond-money-claim"
db_host = "prod-data-lb.moneyclaim.reform.hmcts.net"
capacity = "2"
