idam_api_url = "http://idam-api-idam-sandbox.service.core-compute-idam-sandbox.internal"
db_host = "pettyfrance.postgres.database.azure.com"
frontend_url = "https://cmc-citizen-frontend-sandbox.service.core-compute-sandbox.internal"
respond_to_claim_url = "https://cmc-citizen-frontend-sandbox.service.core-compute-sandbox.internal/first-contact/start"
ccd_enabled = "false"
ccd_async_enabled = "false"
dm_url = "http://dm-store-sandbox.service.core-compute-sandbox.internal"
save_claim_state_enabled = "true"
