idam_api_url = "http://betaDevBccidamAppLB.reform.hmcts.net"
db_host = "test-data-lb.moneyclaim.reform.hmcts.net"
frontend_url = "https://cmc-citizen-frontend-sprod.service.core-compute-sprod.internal"
capacity = "2"
respond_to_claim_url = "https://cmc-citizen-frontend-sprod.service.core-compute-sprod.internal/first-contact/start"
enable_staff_email = "false"
ccd_enabled = "false"
ccd_async_enabled = "true"
