package uk.gov.hmcts.cmc.domain.models;

public enum ClaimDocumentType {
    ORDER_DIRECTIONS,
    ORDER_SANCTIONS,
    SEALED_CLAIM,
    CLAIM_ISSUE_RECEIPT,
    DEFENDANT_RESPONSE_RECEIPT,
    CCJ_REQUEST,
    SETTLEMENT_AGREEMENT,
    DEFENDANT_PIN_LETTER,
    CLAIMANT_DIRECTIONS_QUESTIONNAIRE,
    COVER_SHEET
}
