package uk.gov.hmcts.cmc.ccd.domain.defendant.statementofmeans;

public enum CCDIncomeType {
    JOB,
    UNIVERSAL_CREDIT,
    JOB_SEEKERS_ALLOWANCE_INCOME_BASES,
    JOB_SEEKERS_ALLOWANCE_CONTRIBUTION_BASED,
    INCOME_SUPPORT,
    WORKING_TAX_CREDIT,
    CHILD_TAX_CREDIT,
    CHILD_BENEFIT,
    COUNCIL_TAX_SUPPORT,
    PENSION,
    OTHER
}
